version: '3.7'

services:

  postgres-db:
    container_name: postgres-db-container
    image: postgres:${POSTGRES_VERSION:-10.5}
    expose:
      - 5432
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-exchange}
      - POSTGRES_USER=${DB_USERNAME:-exchange}
      - POSTGRES_DB=${DB_NAME:-exchange_db}
    restart: unless-stopped
    networks:
      - exchange-backend

  exchange-server:
    container_name: exchange-application-container
    build:
      context: .
    image: exchange-application:${APPLICATION_VERSION:-1.0}
    expose:
      - 8081
    ports:
      - ${APPLICATION_PORT:-8081}:8081
    environment:
      - DB_URL=${DB_URL:-postgres-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-exchange_db}
      - DB_SCHEMA=${DB_SCHEMA:-core}
      - DB_USERNAME=${DB_USERNAME:-exchange}
      - DB_PASSWORD=${DB_PASSWORD:-exchange}
    depends_on:
      - postgres-db
    links:
      - postgres-db
    networks:
      - exchange-backend

volumes:
  postgres-db-volume:

networks:
  exchange-backend:
    driver: bridge