spring:

  application:
    name: exchange-application

  banner:
    location: classpath:banner.txt

  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:exchange_db}?currentSchema=${DB_SCHEMA:core}
    username: ${DB_USERNAME:exchange}
    password: ${DB_PASSWORD:exchange}